language: common-lisp
sudo: false

addons:
  apt:
    packages:
    - zip

env:
  global:
  - GAMEKIT_SYSTEM_NAME: notalone-again
  - GAMEKIT_APPLICATION_PACKAGE: notalone-again
  - GAMEKIT_APPLICATION_MAIN_CLASS: notalone-again
  - PATH: ~/bin/:$PATH
  - GAMEKIT_TARGET_PACKAGE: $GAMEKIT_SYSTEM_NAME-x86-64-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip
  - GAMEKIT_BUILD_DIR: /tmp/$GAMEKIT_SYSTEM_NAME
  - secure: "rfKaTa3FsBukWfnIeNbWL8CVI2wUS+c2SsZRraFozuLV/VgO3fMA+li1tZTU3nTeq//JB9OxyPDr+9Hbpoce9QMugg8KWGRE5jYhVHtngjjDo6yKiUk3oKI8D8VX43c922ZeCWyOL9NiBysF7CSU2tlJy4QzTy7P9fhHY+oBRKxAyYG2w9c1LLOVTV23cO0Xs3bfk9QO2D+wPBco4HygYSVKdsgw4AzTxAZl2+p3sOihq1Rzo1FxQiwSWsaiDQVCKuzIvE/E7JYUtV8KeR+/Z/MUoOqZBoUh3SPNAk080BFY7UbkNfAmc0AlSKPkCe58CWH6+bjTHy+LUQdja8G506giIEAvTvKxLEqjXNkuJAC0o+2u6asQKQp7ty2UEdCLWAHKZ06MRtl+J8C9BB+y+PpnI8vEnhjqA6lVHJByTV45ysvAc3z4clHxJWyQe7ui2eIf4eP2fSlI/BOOQO5A1TxWZw0Ie/4wpFn0twW3aSlABBjMXA89vyHmmVxGMQlOOVhkV4Edg7gXb/1URwd/r+3YlqeqW9A64prv8DB4VTYZz24DF6b4fNH6S/icpgfdfAIL22Q0VS9ebg4YqINpPYz9+IapcQ4+t5zO4tDPeV04w8BVUVEAsqW7fRp95uTz0oWCEmZ+IKMkcnDAsVk6iQ0awsMqPZ5JqKPyFkFhnuU="

branches:
  only:
    - "/^v\\d+(\\.\\d+)+$/"

os:
  - linux
  - osx

install:
  - curl -L http://bodge.borodust.org/files/install.sh | sh

script:
  - >
    lisp $HOME/bodge/scripts/build-experimental-gamekit-system.lisp
    $GAMEKIT_SYSTEM_NAME $GAMEKIT_APPLICATION_PACKAGE $GAMEKIT_APPLICATION_MAIN_CLASS
    $TRAVIS_BUILD_DIR
    $GAMEKIT_BUILD_DIR

before_deploy:
  - mv "$GAMEKIT_BUILD_DIR/$GAMEKIT_SYSTEM_NAME.zip" $GAMEKIT_TARGET_PACKAGE

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file: $GAMEKIT_TARGET_PACKAGE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
